In [7]:
import numpy as np
import numpy.linalg as nl

In [10]:
nmax=4
H = np.zeros((nmax,nmax),float)
XAXB = np.array([[0, 0, 0, 1],[0, 0, 1, 0],[0, 1, 0, 0],[1, 0, 0, 0]])
YAYB = np.array([[0, 0, 0, -1],[0, 0, 1, 0],[0, 1, 0, 0],[-1, 0, 0, 0]])
ZAZB = np.array([[1, 0, 0, 0],[0, -1, 0, 0],[0, 0, -1, 0],[0, 0, 0, 1]])
SASB = XAXB + YAYB + ZAZB - 3*ZAZB
print('\n Hamiltonian without mu^2/r^3 factor: \n', SASB ,'\n')
es , ev = nl.eig(SASB)
print('Eigenvalues:\n', np.round(es,2) ,'\n')
print('Eigenvectors(in columns):\n' , ev , '\n' )


 Hamiltonian without mu^2/r^3 factor: 
 [[-2  0  0  0]
 [ 0  2  2  0]
 [ 0  2  2  0]
 [ 0  0  0 -2]] 

Eigenvalues:
 [ 4.  0. -2. -2.] 

Eigenvectors(in columns):
 [[ 0.          0.          1.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]
 [ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.          0.          0.          1.        ]] 



In [11]:
phi1 = (ev[0,0], ev[1,0], ev[2,0], ev[3,0]) # Eigenvectors
phi4 = (ev[0,1], ev[1,1], ev[2,1], ev[3,1])
phi3 = (ev[0,2], ev[1,2], ev[2,2], ev[3,2])
phi2 = (ev[0,3], ev[1,3], ev[2,3], ev[3,3])
basis=[phi1, phi2 , phi3 , phi4] # List eigenvectors

for i in range(0 , nmax): # Hamiltonian in new basis
      for j in range(0 , nmax):
          term     = np.dot(SASB,basis[i])
          H[i , j] = np.round(np.dot(basis[j],term),2)
print(" Hamiltonian in Eigenvector Basis: \n " ,H)

 Hamiltonian in Eigenvector Basis: 
  [[ 4.  0.  0.  0.]
 [ 0. -2.  0.  0.]
 [ 0.  0. -2.  0.]
 [ 0.  0.  0.  0.]]
